### ISSUE TITLE
Error: Something went wrong while executing your query

### ISSUE THREAD

**Issue by Mr-KayJayDee** [teoxoy/profile-readme-stats#6] opened 2021-04-19 18:12 UTC
Here the screenshot of the error.

![image](https://user-images.githubusercontent.com/46600662/115282975-1a40b700-a14b-11eb-8485-66d1974b9da6.png)

The code they are asking to give:
`
07C2:4FCA:E5D17F:29EBB3A:607DC6CE
`

And my workflow config:

```yml
on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - master
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4 # here i just added the latest actions/checkout version because the v2 wasn't working
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update README.md statistics
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push
        fi
```

**Comment by teoxoy** [comment] 2021-04-19 18:35
That error is from Github's GraphQL API. Is this happening every time the action runs?

**Comment by Mr-KayJayDee** [comment] 2021-04-19 18:58
Yes it is happenning every time the action runs.

**Comment by teoxoy** [comment] 2021-04-19 19:35
Maybe you can report it [here](https://support.github.com/contact) then.

**Comment by teoxoy** [comment] 2021-04-20 11:25
Will close this. Feel free to reopen if you think the issue is with the action itself.

**Closed by teoxoy** 2021-04-20 11:25 UTC

**Comment by Mr-KayJayDee** [comment] 2021-05-03 17:09
Hello, I got an answer from github with this issue. 

Here is: 

```
Hi there,

Thanks for reaching out and I apologize for the delay in getting back to you on this

Looking at the logs, It looks like you are hitting timeouts on our GraphQL API. All API requests, both for the REST API and GraphQL API, have a 10 second limit on execution time. If that limit is reached for a request, the request is terminated. That behaviour is expected and we're not able to increase this 10-second limit.

This normally happens when the query used involves too much data, so the way to avoid timeouts is to write smaller queries. Requests that touch a lot of data should be split into several smaller queries and executed separately.

Hope this helps and sorry again for the delay.
```

How can I split into several queries ?

Thanks for the answer. 🙃
